Neos:
  Neos:
    fusion:
      autoInclude:
        Shel.Neos.Booster: true

Shel:
  Neos:
    Booster:
      preloadNodes: true
      preloadDocumentNodes: true
      aspects:
        enabled: true
      timedContent:
        enabled: false
